### ISSUE TITLE
Deploy hopannotation1-export

### ISSUE THREAD

**Issue by cristinaleonr** [m-lab/stats-pipeline#97]
- [x] Source hopannotation1 archives from sandbox, staging, or public archives.
- [x] Adjust existing cron job to do hopannotation1 export.
- [x] Run export process.
- [x] Make sure the GCS transfer job is enabled (add ndt/hopannotation1 prefix to job configuration)
- [x] Allow synthetic hopannotation1 export parsing to complete.
- [x] Rerun annotation export e2e.
- [x] Run query to verify dates under `mlab-staging.raw_ndt.hopannotation1`.
- [x] Repeat all steps in production.

**Comment by cristinaleonr** [comment]
Verification in staging.

```
select date, count(*) as total
from `mlab-staging.raw_ndt.hopannotation1`
where date > date('2019-03-28')
group by date
order by date 
```
![Screenshot 2022-01-17 2 12 14 PM](https://user-images.githubusercontent.com/21001496/149825857-45454647-f446-48ae-8032-65b7d075b0d3.png)

**Comment by cristinaleonr** [comment]
Verification in prod.

```
select date, count(*) as total
from `mlab-oti.raw_ndt.hopannotation1`
where date > date('2019-03-28')
group by date
order by date 
```

![image](https://user-images.githubusercontent.com/21001496/151820160-d8b3de86-bb2c-43d4-8f39-f5529521f9cf.png)

**Comment by cristinaleonr** [comment]
@stephen-soltesz LGTY?

**Comment by stephen-soltesz** [comment]
Nice!
